version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - product-service
    networks:
      - microservices-net

  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    networks:
      - microservices-net

  product-service:
    build:
      context: ./product-service
    ports:
      - "5002:5002"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
